# Generated by Django 3.1.3 on 2020-11-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='ready',
            field=models.BooleanField(default=False),
        ),
    ]
