# Generated by Django 3.1.3 on 2020-11-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diffing', '0002_job_ready'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='file_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
